// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgbfqcbqfdzrtbtlycve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYmZxY2JxZmR6cnRidGx5Y3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NzU4ODUsImV4cCI6MjA3OTE1MTg4NX0.Z0BN652DB2byne5eOZB5Qj6dFX_Lhxm_Yj-C0MiFTYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Health check to ensure auth is ready before critical operations
export const waitForAuth = async (maxWait = 3000): Promise<boolean> => {
  const startTime = Date.now();
  console.log('[SupabaseClient] ⏳ Waiting for auth to be ready...');
  
  while (Date.now() - startTime < maxWait) {
    const { data: { session } } = await supabase.auth.getSession();
    if (session?.access_token) {
      console.log('[SupabaseClient] ✅ Auth ready with valid token');
      return true;
    }
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  console.warn('[SupabaseClient] ⚠️ Auth timeout - no valid token after', maxWait, 'ms');
  return false;
};

/**
 * Ensures there's a valid session, refreshing if necessary
 */
export const ensureValidSession = async (): Promise<boolean> => {
  console.log('[SupabaseClient] Verificando validade da sessão...');
  
  const { data: { session }, error } = await supabase.auth.getSession();
  
  if (error) {
    console.error('[SupabaseClient] ❌ Erro ao obter sessão:', error);
    return false;
  }
  
  if (!session) {
    console.warn('[SupabaseClient] ⚠️ Sem sessão ativa');
    return false;
  }
  
  // Check if token is close to expiring (less than 5 minutes)
  const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
  const now = Date.now();
  const fiveMinutes = 5 * 60 * 1000;
  
  if (expiresAt - now < fiveMinutes) {
    console.log('[SupabaseClient] 🔄 Token próximo de expirar, renovando...');
    
    const { data: { session: newSession }, error: refreshError } = 
      await supabase.auth.refreshSession();
    
    if (refreshError || !newSession) {
      console.error('[SupabaseClient] ❌ Falha ao renovar sessão');
      return false;
    }
    
    console.log('[SupabaseClient] ✅ Sessão renovada com sucesso');
    return true;
  }
  
  console.log('[SupabaseClient] ✅ Sessão válida');
  return true;
};

/**
 * Verifica se auth.uid() retorna um valor válido
 * Testa ANTES de fazer operações críticas com RLS
 */
export const verifyAuthUid = async (): Promise<{ valid: boolean; uid: string | null }> => {
  try {
    console.log('[SupabaseClient] 🔍 Testando auth.uid()...');
    
    // Usar a função SQL que criamos para testar auth.uid()
    const { data, error } = await supabase
      .rpc('get_current_user_id');
    
    if (error) {
      console.error('[SupabaseClient] ❌ Erro ao testar auth.uid():', error);
      return { valid: false, uid: null };
    }
    
    if (!data) {
      console.warn('[SupabaseClient] ⚠️ auth.uid() retornou NULL');
      return { valid: false, uid: null };
    }
    
    console.log('[SupabaseClient] ✅ auth.uid() válido:', data);
    return { valid: true, uid: data };
  } catch (error) {
    console.error('[SupabaseClient] ❌ Exceção ao testar auth.uid():', error);
    return { valid: false, uid: null };
  }
};

/**
 * Força o Supabase client a recarregar o token do localStorage
 */
export const forceTokenReload = async (): Promise<boolean> => {
  try {
    console.log('[SupabaseClient] 🔄 Forçando reload do token...');
    
    // Pegar o token do localStorage
    const storageKey = `sb-${SUPABASE_URL.split('//')[1].split('.')[0]}-auth-token`;
    const storedSession = localStorage.getItem(storageKey);
    
    if (!storedSession) {
      console.error('[SupabaseClient] ❌ Nenhum token no localStorage');
      return false;
    }
    
    // Forçar o Supabase client a usar a sessão armazenada
    const { data: { session }, error } = await supabase.auth.setSession(
      JSON.parse(storedSession)
    );
    
    if (error || !session) {
      console.error('[SupabaseClient] ❌ Erro ao recarregar sessão:', error);
      return false;
    }
    
    console.log('[SupabaseClient] ✅ Token recarregado com sucesso');
    return true;
  } catch (error) {
    console.error('[SupabaseClient] ❌ Exceção ao recarregar token:', error);
    return false;
  }
};