// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgbfqcbqfdzrtbtlycve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYmZxY2JxZmR6cnRidGx5Y3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NzU4ODUsImV4cCI6MjA3OTE1MTg4NX0.Z0BN652DB2byne5eOZB5Qj6dFX_Lhxm_Yj-C0MiFTYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});