// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgbfqcbqfdzrtbtlycve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYmZxY2JxZmR6cnRidGx5Y3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NzU4ODUsImV4cCI6MjA3OTE1MTg4NX0.Z0BN652DB2byne5eOZB5Qj6dFX_Lhxm_Yj-C0MiFTYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Health check to ensure auth is ready before critical operations
export const waitForAuth = async (maxWait = 3000): Promise<boolean> => {
  const startTime = Date.now();
  console.log('[SupabaseClient] ⏳ Waiting for auth to be ready...');
  
  while (Date.now() - startTime < maxWait) {
    const { data: { session } } = await supabase.auth.getSession();
    if (session?.access_token) {
      console.log('[SupabaseClient] ✅ Auth ready with valid token');
      return true;
    }
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  console.warn('[SupabaseClient] ⚠️ Auth timeout - no valid token after', maxWait, 'ms');
  return false;
};